name: Update calendar.xml

on:
  schedule:
    - cron: '0 5 * * *'  # Täglich 05:00 UTC
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run calendar fetcher
        run: npm start
        env:
          MYFXBOOK_EMAIL: ${{ secrets.MYFXBOOK_EMAIL }}
          MYFXBOOK_PASSWORD: ${{ secrets.MYFXBOOK_PASSWORD }}

      - name: Commit updated XML
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add calendar.xml
          git commit -m "Update calendar.xml" || echo "No changes"
          git push
